[project]
name = "male01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deeptabular",
    "numpy>=1.26.4",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
]

[tool.uv.sources]
deeptabular = { git = "https://github.com/OpenTabular/DeepTabular.git" }
